/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Liveness
         * @description Report process liveness without querying PostgreSQL.
         */
        get: operations["get_liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Readiness
         * @description Report readiness from a fresh database probe.
         *
         *     Args:
         *         request: Current request used to access the application-scoped engine.
         *         response: Mutable response used to return HTTP 503 when unavailable.
         *
         *     Returns:
         *         A safe response containing only the public database state.
         */
        get: operations["get_readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cards
         * @description List compact owned card summaries with language and tag filtering.
         */
        get: operations["list_cards_v1_cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_v1_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Card
         * @description Return complete multilingual content for one owned card.
         */
        get: operations["get_card_v1_cards__card_id__get"];
        put?: never;
        post?: never;
        /** Archive Card */
        delete: operations["archive_card_v1_cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card */
        patch: operations["update_card_v1_cards__card_id__patch"];
        trace?: never;
    };
    "/v1/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decks
         * @description List owned decks in stable most-recently-updated order.
         */
        get: operations["list_decks_v1_decks_get"];
        put?: never;
        /** Create Deck */
        post: operations["create_deck_v1_decks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deck
         * @description Return one owned deck without disclosing cross-owner existence.
         */
        get: operations["get_deck_v1_decks__deck_id__get"];
        put?: never;
        post?: never;
        /** Archive Deck */
        delete: operations["archive_deck_v1_decks__deck_id__delete"];
        options?: never;
        head?: never;
        /** Update Deck */
        patch: operations["update_deck_v1_decks__deck_id__patch"];
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the authenticated internal identity without exposing Google subject.
         */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Reviews
         * @description Commit one bounded review batch or replay its original result.
         */
        post: operations["submit_reviews_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Due Reviews
         * @description Return active due cards using one server-time snapshot across pages.
         */
        get: operations["list_due_reviews_v1_reviews_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardCreate */
        CardCreate: {
            /**
             * Antonyms
             * @default []
             */
            antonyms: string[];
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Example Source */
            example_source?: string | null;
            /** Example Translation */
            example_translation?: string | null;
            /** Learned On */
            learned_on?: string | null;
            /** Meaning */
            meaning: string;
            /** Note */
            note?: string | null;
            /** Part Of Speech */
            part_of_speech?: ("noun" | "verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "preposition" | "conjunction" | "interjection" | "particle" | "auxiliary" | "numeral" | "phrase" | "other") | null;
            /** Part Of Speech Detail */
            part_of_speech_detail?: string | null;
            /** Pronunciation */
            pronunciation?: string | null;
            /** Reading */
            reading?: string | null;
            /** Romanization */
            romanization?: string | null;
            /** Supplementary Note */
            supplementary_note?: string | null;
            /**
             * Synonyms
             * @default []
             */
            synonyms: string[];
            /** Target Language Definition */
            target_language_definition?: string | null;
            /** Term */
            term: string;
        };
        /** CardDetail */
        CardDetail: {
            /** Antonyms */
            antonyms: string[];
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            deck: components["schemas"]["DeckSummary"];
            /** Example Sentence */
            example_sentence: string | null;
            /** Example Source */
            example_source: string | null;
            /** Example Translation */
            example_translation: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Learned On */
            learned_on: string | null;
            /** Meaning */
            meaning: string;
            /** Note */
            note: string | null;
            /** Part Of Speech */
            part_of_speech: string | null;
            /** Part Of Speech Detail */
            part_of_speech_detail: string | null;
            /** Pronunciation */
            pronunciation: string | null;
            /** Reading */
            reading: string | null;
            review_state: components["schemas"]["ReviewState"] | null;
            /** Romanization */
            romanization: string | null;
            /** Supplementary Note */
            supplementary_note: string | null;
            /** Synonyms */
            synonyms: string[];
            /** Tags */
            tags: components["schemas"]["TagSummary"][];
            /** Target Language Definition */
            target_language_definition: string | null;
            /** Term */
            term: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** CardSummary */
        CardSummary: {
            /** Archived At */
            archived_at: string | null;
            deck: components["schemas"]["DeckSummary"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Meaning */
            meaning: string;
            /** Part Of Speech */
            part_of_speech: string | null;
            /** Pronunciation */
            pronunciation: string | null;
            /** Reading */
            reading: string | null;
            /** Romanization */
            romanization: string | null;
            /** Term */
            term: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** CardUpdate */
        CardUpdate: {
            /** Antonyms */
            antonyms?: string[] | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Example Source */
            example_source?: string | null;
            /** Example Translation */
            example_translation?: string | null;
            /** Learned On */
            learned_on?: string | null;
            /** Meaning */
            meaning?: string | null;
            /** Note */
            note?: string | null;
            /** Part Of Speech */
            part_of_speech?: ("noun" | "verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "preposition" | "conjunction" | "interjection" | "particle" | "auxiliary" | "numeral" | "phrase" | "other") | null;
            /** Part Of Speech Detail */
            part_of_speech_detail?: string | null;
            /** Pronunciation */
            pronunciation?: string | null;
            /** Reading */
            reading?: string | null;
            /** Romanization */
            romanization?: string | null;
            /** Supplementary Note */
            supplementary_note?: string | null;
            /** Synonyms */
            synonyms?: string[] | null;
            /** Target Language Definition */
            target_language_definition?: string | null;
            /** Term */
            term?: string | null;
            /** Version */
            version: number;
        };
        /** Deck */
        Deck: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Explanation Language
             * @enum {string}
             */
            explanation_language: "en" | "ja" | "zh-TW";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Target Language
             * @enum {string}
             */
            target_language: "en" | "ja";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** DeckCreate */
        DeckCreate: {
            /**
             * Explanation Language
             * @enum {string}
             */
            explanation_language: "en" | "ja" | "zh-TW";
            /**
             * Target Language
             * @enum {string}
             */
            target_language: "en" | "ja";
            /** Title */
            title: string;
        };
        /** DeckSummary */
        DeckSummary: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Explanation Language
             * @enum {string}
             */
            explanation_language: "en" | "ja" | "zh-TW";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Target Language
             * @enum {string}
             */
            target_language: "en" | "ja";
            /** Title */
            title: string;
        };
        /** DeckUpdate */
        DeckUpdate: {
            /** Explanation Language */
            explanation_language?: ("en" | "ja" | "zh-TW") | null;
            /** Title */
            title?: string | null;
            /** Version */
            version: number;
        };
        /**
         * DueCard
         * @description A complete review-ready card; review_state is always populated.
         */
        DueCard: {
            /** Antonyms */
            antonyms: string[];
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            deck: components["schemas"]["DeckSummary"];
            /** Example Sentence */
            example_sentence: string | null;
            /** Example Source */
            example_source: string | null;
            /** Example Translation */
            example_translation: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Learned On */
            learned_on: string | null;
            /** Meaning */
            meaning: string;
            /** Note */
            note: string | null;
            /** Part Of Speech */
            part_of_speech: string | null;
            /** Part Of Speech Detail */
            part_of_speech_detail: string | null;
            /** Pronunciation */
            pronunciation: string | null;
            /** Reading */
            reading: string | null;
            review_state: components["schemas"]["ReviewState"];
            /** Romanization */
            romanization: string | null;
            /** Supplementary Note */
            supplementary_note: string | null;
            /** Synonyms */
            synonyms: string[];
            /** Tags */
            tags: components["schemas"]["TagSummary"][];
            /** Target Language Definition */
            target_language_definition: string | null;
            /** Term */
            term: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LivenessResponse
         * @description Response returned when the API process can handle requests.
         */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Page[CardSummary] */
        Page_CardSummary_: {
            /** Items */
            items: components["schemas"]["CardSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Deck] */
        Page_Deck_: {
            /** Items */
            items: components["schemas"]["Deck"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[DueCard] */
        Page_DueCard_: {
            /** Items */
            items: components["schemas"]["DueCard"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ReadinessChecks
         * @description Public dependency states included in a readiness response.
         */
        ReadinessChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /**
         * ReadinessResponse
         * @description Response describing whether the API is ready to receive traffic.
         */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** ReviewResult */
        ReviewResult: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Items */
            items: components["schemas"]["ReviewResultItem"][];
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /** ReviewResultItem */
        ReviewResultItem: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "no" | "no_a_bit" | "yes_a_bit" | "yes";
            /** Event Id */
            event_id: number;
            previous_state: components["schemas"]["TransitionState"];
            /** Quality */
            quality: number;
            resulting_state: components["schemas"]["TransitionState"];
        };
        /** ReviewState */
        ReviewState: {
            /** Ease Factor */
            ease_factor: string;
            /** Interval Days */
            interval_days: number;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Next Review At
             * Format: date-time
             */
            next_review_at: string;
            /** Review Stage */
            review_stage: number;
            /** Version */
            version: number;
        };
        /** ReviewSubmission */
        ReviewSubmission: {
            /** Items */
            items: components["schemas"]["ReviewSubmissionItem"][];
        };
        /** ReviewSubmissionItem */
        ReviewSubmissionItem: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "no" | "no_a_bit" | "yes_a_bit" | "yes";
            /** Expected Version */
            expected_version: number;
        };
        /** TagSummary */
        TagSummary: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** TransitionState */
        TransitionState: {
            /** Ease Factor */
            ease_factor: string;
            /** Interval Days */
            interval_days: number;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Next Review At
             * Format: date-time
             */
            next_review_at: string;
            /** Review Stage */
            review_stage: number;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    get_readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_cards_v1_cards_get: {
        parameters: {
            query?: {
                deck_id?: string | null;
                target_language?: ("en" | "ja") | null;
                status?: "active" | "archived" | "all";
                tag_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CardSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_v1_cards_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_v1_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_card_v1_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_v1_cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decks_v1_decks_get: {
        parameters: {
            query?: {
                target_language?: ("en" | "ja") | null;
                status?: "active" | "archived" | "all";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Deck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deck_v1_decks_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deck_v1_decks__deck_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_deck_v1_decks__deck_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deck_v1_decks__deck_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submit_reviews_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_due_reviews_v1_reviews_due_get: {
        parameters: {
            query: {
                target_language: "en" | "ja";
                deck_id?: string[] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DueCard_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
