import type { WordItem } from "$lib/types";

export const mockWordItems: WordItem[] = [
  {
    id: "8",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "patisserie",
    type: "vocabulary",
    phonics: "/pəˈtɪs.ər.i/",
    chineseExplain: "蛋糕店",
    engExplain: "a shop that sells cakes and pastries",
    synonyms: "cake shop, bakery",
    antonyms: "",
    tags: "food",
    note: "common",
    supplementary: "",
    example: "I bought some macarons from the patisserie near my house.",
    status: "active",
    reviewStage: 1,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-23T16:00:00.000Z",
    createdDate: "",
  },
  {
    id: "4",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "speciality",
    type: "vocabulary",
    phonics: "/ˌspeʃ.iˈæl.ə.t̬i/",
    chineseExplain: "擅長、專長",
    engExplain:
      "a product, skill, or service that a person or place is especially known for",
    synonyms: "forte, strength, expertise",
    antonyms: "weakness",
    tags: "food,skills",
    note: "common",
    supplementary: "speciality coffee (特色咖啡)\n to specialize in something",
    example:
      "A: I’m a chef.\nB: What’s your speciality?\nA: I make a good risotto.",
    status: "active",
    reviewStage: 2,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-23T16:00:00.000Z",
    createdDate: "",
  },
  {
    id: "2",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "preliminary",
    type: "vocabulary",
    phonics: "/prɪˈlɪm.ə.ner.i/",
    chineseExplain: "初步的",
    engExplain: "happening before a more important action or event",
    synonyms: "initial, preparatory",
    antonyms: "final",
    tags: "process",
    note: "common",
    supplementary: "",
    example: "",
    status: "active",
    reviewStage: 1,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-23T16:00:00.000Z",
    createdDate: "",
  },
  {
    id: "1",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "regular milk",
    type: "vocabulary",
    phonics: "/ˈreɡ.jə.lɚ mɪlk/",
    chineseExplain: "牛奶（一般）",
    engExplain: "milk that comes from cows",
    synonyms: "dairy milk",
    antonyms: "plant-based milk",
    tags: "food",
    note: "common",
    supplementary: "",
    example: "Most people drink regular milk with their cereal.",
    status: "active",
    reviewStage: 1,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-23T16:00:00.000Z",
    createdDate: "",
  },
  {
    id: "10",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "plant-based milk",
    type: "vocabulary",
    phonics: "/plænt beɪst mɪlk/",
    chineseExplain: "植物奶",
    engExplain: "milk made from plants like oats, almonds, soy, etc.",
    synonyms: "non-dairy milk",
    antonyms: "regular milk",
    tags: "food",
    note: "common",
    supplementary: "",
    example: "Almond milk is a popular plant-based milk.",
    status: "active",
    reviewStage: 2,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-24T16:00:00.000Z",
    createdDate: "",
  },
  {
    id: "7",
    lessonDate: "2025-08-13T16:00:00.000Z",
    content: "savory",
    type: "vocabulary",
    phonics: "/ˈseɪ.vɚ.i/",
    chineseExplain: "鹹的（非甜）",
    engExplain: "tasting of salt or spices and not sweet",
    synonyms: "salty, flavorful",
    antonyms: "sweet",
    tags: "food",
    note: "common",
    supplementary: "",
    example: "I prefer savory snacks over sweet ones.",
    status: "active",
    reviewStage: 2,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReview: "",
    nextReview: "2025-08-23T16:00:00.000Z",
    createdDate: "",
  },
];
